- name: Generate alias config file
  ansible.builtin.template:
    dest: "/home/{{ ansible_user }}/.bashrc"
    src: "bashrc.j2"
    mode: "0700"

- name: "Update apt"
  become: true
  apt:
    update_cache: yes

- name: "Install common dependencies"
  apt:
    update_cache: yes
    name:
      - net-tools
      - curl
    state: present

- name: "Clean cache"
  become: true
  apt:
    autoclean: yes
    autoremove: yes