[localhost]
localhost ansible_connection=local ansible_become_password=m

[server]
magrondiS ansible_host=192.168.56.110  ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/magrondiS/virtualbox/private_key

[serverWorker]
magrondiSW1 ansible_host=192.168.56.111  ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/magrondiS/virtualbox/private_key
magrondiSW2 ansible_host=192.168.56.112  ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/magrondiS/virtualbox/private_key
magrondiSW3 ansible_host=192.168.56.113  ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/magrondiS/virtualbox/private_key

[servers]
magrondiS ansible_host=192.168.56.110 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/magrondiS/virtualbox/private_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'