- name: Setup SSH keys
  hosts:
    - cluser
  become: yes
  tasks:
    - name: Add host SSH public key to vagrant user
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Install common dependencies
  hosts:
  - cluser
  become: yes
  roles:
    - common


- name: Install Docker
  hosts:
  - cluser
  become: yes
  roles:
    - docker_installation


- name: Install K3D & configure cluster
  hosts:
  - cluser
  become: yes
  roles:
    - k3d

