apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://localhost:30081'
                gitlab_rails['initial_root_password'] = 'MonMotDePasse123!'
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081