apiVersion: v1
kind: Service
metadata:
  name: will-app-external
  namespace: dev
spec:
  type: NodePort
  selector:
    app: will-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30090