- name: Install K3s server
  shell: curl -sfL https://get.k3s.io | sh -s - server --node-ip=192.168.56.110 --advertise-address=192.168.56.110 --tls-san=192.168.56.110
  when: k3s_is_server

- name: Wait for K3s API
  wait_for:
    host: 127.0.0.1
    port: 6443
    timeout: 60
  when: k3s_is_server

- name: Wait for token file
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
    timeout: 60
  when: k3s_is_server

- name: Read token from server
  command: cat /var/lib/rancher/k3s/server/node-token
  register: server_token
  when: k3s_is_server

- name: Save token to local file
  local_action:
    module: copy
    content: "{{ server_token.stdout }}"
    dest: "/tmp/k3s_token.txt"
    mode: "0700"
  become: false
  when: k3s_is_server

- name: Read token from local file
  set_fact:
    k3s_token: "{{ lookup('file', '/tmp/k3s_token.txt') | trim }}"
  when: not k3s_is_server

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL={{ k3s_server_url }} \
    K3S_TOKEN={{ k3s_token }} \
    sh -s - --node-ip={{ ansible_host }}
  when: not k3s_is_server