Vagrant.configure("2") do |config|

    NODES = [
     { :hostname => "fsulvacS", :name => "fsulvac", :ip => "192.168.56.110", :cpu => 1, :memory => 2048, :box => "bento/ubuntu-24.04"},
    ]

    NODES.each do |node|
        config.vm.define node[:hostname] do |server|
            server.vm.hostname = node[:hostname]
            server.vm.box = node[:box]
            server.vm.network "private_network", ip: node[:ip]
            server.vm.provider "virtualbox" do |vb|
                vb.name = node[:name]
                vb.memory = node[:memory]
                vb.cpus = node[:cpu]
            end
            
            server.vm.provision "shell", path: "scripts/server.sh"
        end
    end
end
