Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "k3s-server"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "p2-k3s-server"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "scripts/server.sh"
end
