- name: Check if Docker is installed
  become: true
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false
- block:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu bionic stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      notify: Restart Docker

    - name: Ensure current user is in docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"


    - name: Clean APT cache
      apt:
        name: clean cache
  
  become: true
  when: docker_installed.rc != 0