k3d_cluster_name: "p3"
argocd_admin_password: "123"
argocd_node_port: 30082

gitlab_pod_port: 30081
gitlab_root_password: "123"

gitea_admin_user: admin
gitea_admin_password: "123"
gitea_node_port: 30081

wil_node_port: 30090
