- name: Copy configs from templates into role tmp folder
  template:
    src: "{{ item.src }}"
    dest: "{{ role_path }}/tmp/{{ item.dest }}"
  loop:
    - { src: "services.yml.j2", dest: "services.yml" }
    - { src: "cluster.yml.j2", dest: "cluster.yml" }
    - { src: "argocd_config.yml", dest: "argocd_config.yml" }

- name: Delete old cluster
  ansible.builtin.shell: k3d cluster delete {{ k3d_cluster_name }} || true

- name: Create cluster
  ansible.builtin.shell: k3d cluster create {{ k3d_cluster_name }} -c {{ role_path }}/tmp/cluster.yml

- name: Wait for nodes
  ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --all --timeout=120s

- name: Create namespaces
  ansible.builtin.shell: kubectl create namespace {{ item }} || true
  loop:
    - argocd
    - gitlab
    - dev

- name: Create GitLab root password secret
  ansible.builtin.shell: |
    kubectl -n gitlab delete secret gitlab-root-password || true
    kubectl -n gitlab create secret generic gitlab-root-password \
      --from-literal=password={{ gitlab_root_password }}

- name: Add GitLab Helm repo
  ansible.builtin.shell: helm repo add gitlab https://charts.gitlab.io || true

- name: Update Helm repo
  ansible.builtin.shell: helm repo update
  ignore_errors: true

- name: Install GitLab (minimal, NodePort)
  ansible.builtin.shell: |
    helm upgrade --install gitlab gitlab/gitlab \
      -n gitlab \
      --set global.hosts.domain=example.com \
      --set global.hosts.externalIP=127.0.0.1 \
      --set global.ingress.enabled=false \
      --set global.ingress.configureCertmanager=false \
      --set installCertmanager=false \
      --set certmanager-issuer.email=dummy@example.com \
      --set global.initialRootPassword.secret=gitlab-root-password \
      --set global.initialRootPassword.key=password \
      --timeout 20m

- name: Apply GitLab NodePort Service
  ansible.builtin.shell: kubectl apply -f {{ role_path }}/tmp/services.yml


- name: Install ArgoCD
  ansible.builtin.shell: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Install bcrypt
  ansible.builtin.pip:
    name: bcrypt
    state: present
  become: true

- name: Hash ArgoCD password
  ansible.builtin.shell: >
    python3 -c "import bcrypt; print(bcrypt.hashpw(b'{{ argocd_admin_password }}', bcrypt.gensalt()).decode())"
  register: password_hash
  no_log: true

- name: Update ArgoCD password
  ansible.builtin.shell: >
    kubectl -n argocd patch secret argocd-secret \
      -p '{"stringData": {"admin.password": "{{ password_hash.stdout }}", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'
  no_log: true

- name: Create gitLab repo secret for argocd
  ansible.builtin.shell: |
    kubectl -n argocd create secret generic gitlab-repo \
      --from-literal=url=http://gitlab-webservice-default.gitlab.svc.cluster.local/root/wil-app.git \
      --from-literal=username=root \
      --from-literal=password={{ gitlab_root_password }} \
      --from-literal=type=git \
      --dry-run=client -o yaml | kubectl apply -f -

- name: Create ArgoCD Application
  ansible.builtin.shell: kubectl apply -f {{ role_path }}/tmp/argocd_config.yml
