---
- name: Delete existing K3D cluster if exists
  ansible.builtin.shell: k3d cluster delete {{ k3d_cluster_name }}
  ignore_errors: true

- name: Create K3D cluster {{ k3d_cluster_name }}
  ansible.builtin.shell: k3d cluster create {{ k3d_cluster_name }} -c roles/configs/templates/cluster.yml

- name: Wait for nodes to be ready
  ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --all --timeout=120s

- name: Create namespaces
  ansible.builtin.shell: kubectl create namespace {{ item }}
  loop:
    - dev
    - argocd

- name: Install ArgoCD
  ansible.builtin.shell: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Wait for ArgoCD server to be ready
  ansible.builtin.shell: kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s


- name: Expose ArgoCD via NodePort
  ansible.builtin.shell: kubectl apply -f roles/configs/templates/argocd_config.yml

- name: Install bcrypt
  ansible.builtin.pip:
    name: bcrypt
    state: present
  become: true

- name: Hash ArgoCD password
  ansible.builtin.shell: >
    python3 -c "import bcrypt; print(bcrypt.hashpw(b'{{ argocd_admin_password }}', bcrypt.gensalt()).decode())"
  register: password_hash
  no_log: true

- name: Update ArgoCD password
  ansible.builtin.shell: >
    kubectl -n argocd patch secret argocd-secret \
      -p '{"stringData": {"admin.password": "{{ password_hash.stdout }}", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'
  no_log: true
