# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
    NODES = [
     { :hostname => "magrondiS", :ip => "192.168.56.110", :cpu => 1, :memory => 2048, :box => "hashicorp/bionic64", },
     { :hostname => "magrondiSW1", :ip => "192.168.56.111", :cpu => 1, :memory => 2048, :box => "hashicorp/bionic64", },
     { :hostname => "magrondiSW2", :ip => "192.168.56.112", :cpu => 1, :memory => 2048, :box => "hashicorp/bionic64", },
     { :hostname => "magrondiSW3", :ip => "192.168.56.113", :cpu => 1, :memory => 2048, :box => "hashicorp/bionic64", }
    ]

    NODES.each do |node|
        config.vm.define node[:hostname] do |server|
            server.vm.hostname = node[:hostname]
            server.vm.box = node[:box]
            server.vm.network "private_network", ip: node[:ip]
            server.vm.provider "virtualbox" do |vb|
                vb.memory = node[:memory]
                vb.cpus = node[:cpu]
            end
        end
    end

  	config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
  		ansible.playbook = "./ansible/playbook.yml"
		ansible.inventory_path = "./ansible/inventory.ini"
  		ansible.groups = {
  			"servers" => ["magrondiS"],
  			"serverWorker" => ["magrondiSW"]
  		}
  	end
end
